agency/urls.py
from django.urls import path
from agency.views import AgencyLV, AgencyDV


app_name = 'agency'
urlpatterns = [
    path('', AgencyLV.as_view(), name='index'),
    path('<int:pk>/', AgencyDV.as_view(), name='detail'),
]

article/urls.py
from django.urls import path, re_path
from article import views
app_name = 'article'
urlpatterns = [
    # Example: /article/
    path('', views.PostLV.as_view(), name='index'),
    # Example: /article/post/ (same as /article/)
    path('post/', views.PostLV.as_view(), name='post_list'),
    # Example: /article/post/django-example/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    # Example: /article/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    # Example: /article/archive/2020/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    # Example: /article/archive/2020/oct/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    # Example: /article/archive/2019/oct/12/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    # Example: /article/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),
    # Example: /article/search/
    path('search/',views.SearchFormView.as_view(),name='search'),

]

midterm/urls.py
from django.contrib import admin
from django.urls import path, include
from midterm.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'), #Home 화면
    path('patient/',include('patient.urls')), #patient url 추가
    path('agency/',include('agency.urls')), # agency url 추가
    path('article/',include('article.urls')), # article url 추가
]

patient/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import ListView, DetailView
from patient.models import Patient_TBL
from patient.views import PatientLV,PatientDV
from patient import views

app_name = 'patient'
urlpatterns = [
    #Exmple:/patient/
    path('',PatientLV.as_view(model=Patient_TBL),name='index'),

    #Example:/patient/index/
    path('<int:pk>/',PatientDV.as_view(model=Patient_TBL),name='detail'),

    # Example: /patient/search/
    path('search/', views.SearchFormView.as_view(), name='search'),
]

agency/models.py
from django.db import models

# Create your models here.
class Agency(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)

    def __str__(self):
        return self.title

article/models.py
from django.db import models
from django.urls import reverse
class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50) #기사제목
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.') # 기사 설명
    content = models.TextField('CONTENT') # 기사 내용
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True) #기사 날짜
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True) # 기사 수정 날짜
    url = models.URLField('URL', unique=True) # 원본 기사 URL
    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'article_posts'
        ordering = ('-modify_dt',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()
    def get_next(self):
        return self.get_next_by_modify_dt()

patient/models.py
from django.db import models

# Create your models here.
class Patient_TBL(models.Model):
    name=models.CharField('NAME',max_length=100,blank=False) #이름
    pnumber = models.CharField('NUMBER',max_length=50,blank=False) # Phone_number
    email = models.CharField('EMAIL', max_length=50, blank=False) # Email 주소
    status = models.CharField('STATUS', max_length=50, blank=False) #환자 상태
    hospital_dt = models.DateTimeField('HOSPITALIZATION_DATE') #입원날짜
    address = models.CharField('ADDRESS', max_length=50, blank=False) #주소
    def __str__(self):
        return self.name

    class Meta:
        ordering = ('id','name','status','hospital_dt')

article/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

patient/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

agency/views.py
from django.views.generic import ListView, DetailView
from agency.models import Agency


class AgencyLV(ListView):
    model = Agency

class AgencyDV(DetailView):
    model = Agency

article/views.py
from django.views.generic import ListView, DetailView
from django.views.generic import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic import DayArchiveView, TodayArchiveView
from article.models import Post
from django.views.generic import FormView #추가 Search Form
from article.forms import PostSearchForm #Search를 위해 추가
from django.db.models import Q #Search를 위해 추가
from django.shortcuts import render #Search를 위해 추가
#--- ListView
class PostLV(ListView):
    model = Post
    template_name = 'article/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2
#--- DetailView
class PostDV(DetailView):
    model = Post
#--- ArchiveView
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'

#--- FormView
class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'article/post_search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        #filter -> icontrains => 대소문자 구분 X
        post_list = Post.objects.filter(Q(title__icontains=searchWord) |  Q(description__icontains=searchWord) | Q(content__icontains=searchWord)).distinct()
        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list
        return render(self.request, self.template_name, context)   # No Redirection

midterm/views.py
from django.views.generic import TemplateView


#--- TemplateView
class HomeView(TemplateView):
    template_name = 'home.html'

patient/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from patient.models import Patient_TBL
from django.views.generic import FormView #추가 Search Form
from patient.forms import PostSearchForm #Search를 위해 추가
from django.db.models import Q #Search를 위해 추가
from django.shortcuts import render #Search를 위해 추가

# Create your views here.
class PatientLV(ListView): # PatientList 클래스형 뷰 정의
    model = Patient_TBL
    context_object_name='patient_tbls' # 템플릿 파일로 넘겨주는 객체 리스트에 대한 컨텍스트 변수명 정의

class PatientDV(DetailView): # PatientDetail 클래스형 뷰 정의
    model = Patient_TBL
#--- FormView
class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'patient/patient_post_search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        #filter -> icontrains => 대소문자 구분 X
        post_list = Patient_TBL.objects.filter(Q(name__icontains=searchWord)|  Q(pnumber__icontains=searchWord) | Q(email__icontains=searchWord)|  Q(status__icontains=searchWord) | Q(hospital_dt__icontains=searchWord)| Q(address__icontains=searchWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)   # No Redirection

agency/templates/agency/agency_detail.html
{% extends "base.html" %}

{% block title %}COVID19 연관기관 상세정보{% endblock %}

{% block content %}

    <h1>{{ object.title }}</h1>

    <ul>
        <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>

{% endblock %}

agency/templates/agency/agency_list.html
{% extends "base.html" %}

{% block title %}COVID19 연관기관 리스트{% endblock %}

{% block content %}

    <h1>Associated Agency List</h1>
    <br>

    <ul>
        {% for agency in object_list %}
        <li><a href="{% url 'agency:detail' agency.id %}">{{ agency }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

article/templates/article/post_all.html
{% extends "base.html" %}
{% block title %}COVID19 관련 기사리스트{% endblock %}
{% block content %}

    <h1>Article List</h1>
    <br>

    {% for post in posts %}
        <h3><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h3>
        {{ post.modify_date|date:"N d, Y" }}
        <p>{{ post.description }}</p>
        <p><a href="{{post.url}}">원본기사링크</a> </p>
    {% endfor %}
    <br>
    <div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
            {% endif %}

            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
            {% endif %}
        </span>

    </div>

{% endblock %}

article/templates/article/post_archive.html
{% extends "base.html" %}
{% block title %}COVID19 기사 Archives{% endblock %}
{% block content %}

    <h1>Article Archives until {% now "N d, Y" %}</h1>

    {% for date in date_list %}
    <a href="{% url 'article:post_year_archive' date|date:'Y' %}"
       class="btn btn-outline-primary btn-sm mx-1">
        Year-{{ date|date:"Y" }}</a>
    {% endfor %}
    <br><br>

    <div>
        <ul>
            {% for post in object_list %}
            <li class="h5">
                {{ post.modify_dt|date:"Y-m-d" }}&emsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

article/templates/article/post_archive_day.html
{% extends "base.html" %}
{% block title %}일자별 COVID19 기사 Archives{% endblock %}
{% block content %}

    <h1>Article Archives for {{ day|date:"N d, Y" }}</h1>
    <br><br>

    <div>
        <ul>
            {% for post in object_list %}
            <li class="h5">
                {{ post.modify_dt|date:"Y-m-d" }}&emsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

article/templates/article/post_archive_month.html
{% extends "base.html" %}
{% block title %}월별 COVID19 기사 Archives{% endblock %}
{% block content %}
    <h1>Article Archives for {{ month|date:"N, Y" }}</h1>
    <br><br>

    <div>
        <ul>
            {% for post in object_list %}
            <li class="h5">
                {{ post.modify_dt|date:"Y-m-d" }}&emsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

article/templates/article/post_archive_year.html
{% extends "base.html" %}
{% block title %}연도별 COVID19 기사 Archives{% endblock %}
{% block content %}

    <h1>Article Archives for {{ year|date:"Y" }}</h1>

    {% for date in date_list %}
    <a href="{% url 'article:post_month_archive' date|date:'Y' date|date:'b' %}"
       class="btn btn-outline-primary btn-sm mx-1">
        {{ date|date:"F" }}</a>
    {% endfor %}

    <br><br>

    <div>
        <ul>
            {% for post in object_list %}
            <li class="h5">
                {{ post.modify_dt|date:"Y-m-d" }}&emsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

article/templates/article/post_detail.html
{% extends "base.html" %}
{% block title %}COVID19 기사{% endblock %}
{% block content %}
    <h2>{{ object.title }}</h2>

    <p>
        {% if object.get_next %}
        <a href="{{ object.get_next.get_absolute_url }}" title="View previous post">
            <i class="fas fa-arrow-circle-left"></i> {{ object.get_next }}
        </a>
        {% endif %}

        {% if object.get_previous %}
        | <a href="{{ object.get_previous.get_absolute_url }}" title="View next post">
        {{ object.get_previous }} <i class="fas fa-arrow-circle-right"></i>
        </a>
        {% endif %}
    </p>

    <div>{{ object.modify_dt|date:"j F Y" }}</div>
    <br>

    <div>
        {{ object.content|linebreaks }}
    </div>
    <div>
        <a href="{{post.url}}" title="원본기사링크">원본기사</a>
    </div>
{% endblock %}

article/templates/article/post_search.html
{% extends "base.html" %}
{% block title %}COVID19 기사 검색{% endblock %}
{% block content %}

    <h1>Article Search</h1>
    <br>

    <form action="." method="post"> {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Submit" class="btn btn-primary btn-sm">
    </form>

    <br/><br/>

    {% if object_list %}
        {% for post in object_list %}
        <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
        {{ post.modify_dt|date:"N d, Y" }}
        <p>{{ post.description }}</p>
        {% endfor %}

    {% elif search_term %}
    <b><i>Search Word({{ search_term }}) Not Found !</i></b>
    {% endif %}

{% endblock %}

patient/templates/patient/patient_post_search.html
{% extends "base.html" %}
{% block title %}COVID19 환자 검색{% endblock %}
{% block content %}

    <h1>Patient Search</h1>
    <br>

    <form action="." method="post"> {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Submit" class="btn btn-primary btn-sm">
    </form>
    
    <br/><br/>
    {% if object_list %}
        {% for post in object_list %}
        <h2><a href = "{%url 'patient:detail' post.id %}">{{post.name}}</a></h2>
        {{ post.modify_dt|date:"N d, Y" }}
        <p>{{ post.pnumber }}</p>
        <p>{{ post.status }}</p>
        <p>{{ post.email }}</p>
        <p>{{ post.hospital_dt }}</p>
        <p>{{ post.address }}</p>
        {% endfor %}

    {% elif search_term %}
    <b><i>Search Word({{ search_term }}) Not Found !</i></b>
    {% endif %}

{% endblock %}

patient/templates/patient/patient_tbl_detail.html
{% extends "base.html" %}
{% block title %}COVID19 환자 정보{% endblock %}
{% block content %}
        <div id = "content">
            <h1>{{object.name}}</h1>
            <table border="1">
                <th></th>
                <tr> <!-- 첫번째 줄-->
                    <td>이름</td>
                    <td>{{object.name}}</td>
                    <td>상태</td>
                    <td>{{object.status}}</td>
                </tr>
                <tr> <!--두번째 줄-->
                    <td>휴대폰번호</td>
                    <td>{{object.pnumber}}</td>
                    <td>이메일</td>
                    <td>{{object.email}}</td>
                </tr>
                <tr> <!--세번째 줄-->
                    <td>주소</td>
                    <td colspan="3">{{object.address}}</td>
                </tr>
                <tr> <!--네번째 줄-->
                    <td>입원날짜</td>
                    <td colspan="3">{{object.hospital_dt}}</td>
                </tr>
            </table>
 {% endblock %}
 

patient/templates/patient/patient_tbl_list.html
{% extends "base.html" %}
{% block title %}COVID19 환자리스트{% endblock %}
{% block content %}

            <h1>Patient List in Seoul</h1>
            <ul>
                {% for patient_tbl in patient_tbls %}
                    <li> <a href = "{%url 'patient:detail' patient_tbl.id %}">{{patient_tbl}}</a></li>
                {% endfor %}
            </ul>

{% endblock %}
            

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Django Web Programming{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    {% block extra-style %}{% endblock %}
</head>

<body style="padding-top:90px;">

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">COVID19 in Seoul</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'home' %}">Home</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'agency:index' %}">Agency_연관기관</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'article:index' %}">Article_기사</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'patient:index' %}">Patient_환자리스트</a></li>

            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Util</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'article:post_archive' %}">Article_Archive</a>
                    <a class="dropdown-item" href="{% url 'article:search' %}">기사검색</a> 
                    <a class="dropdown-item" href="{% url 'patient:search' %}">환자검색</a>
                </div>
            </li>
        </ul>

    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://kit.fontawesome.com/c998a172fe.js"></script>
{% block extra-script %}{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}COVID19 In Seoul{% endblock %}

{% block extra-style %}
<style type="text/css">
.home-image {
    background-image: url("{% static 'img/covid19_seoul.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    padding: 20px 0 0 20px;
}
.title {
    color: #c80;
    font-weight: bold;
}
.powered {
    position: relative;
    top: 77%;
    color: #cc0;
    font-style: italic;
}
</style>
{% endblock %}

{% block content %}
    <div class="home-image">
    </div>
    
    <hr style="margin: 10px 0;">
    <div class="row text-center">
        <div class="col-sm-6">
            <h3>Agency App</h3>
            <p> 위 앱에서는 COVID19와 연관 되어있는 한국의 기관들의 
                Uniform Resource Identifier (URI)를 포함하고 있습니다.
                This application contains the Uniform Resource Identifiers (URIs) of Korean institutions related to COVID19.</p>
        </div>
        <div class="col-sm-6">
            <h3>Article App</h3>
            <p>위 앱에서는 COVID19와 연관 되어있는 각종 기사들을 포함하고 있습니다.
                This application contains various articles related to COVID19. </p>
        </div>
        <div class="col-sm-6">
            <h3>patient App</h3>
            <p> 위 앱에서는 COVID19에 걸린 서울시에 거주하는 환자들의 정보를 제공합니다. 
                This application provides information on patients in Seoul with COVID19.</p>
        </div>
    </div>
{% endblock content %}

{% block footer %}
<footer class="fixed-bottom bg-info">
    <div class="text-white font-italic text-right mr-5">Copyright &copy; 2019 DjangoBook by shkim</div>
</footer>
{% endblock %}